# Generated by Django 2.1.11 on 2022-02-09 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('state', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('genere', models.CharField(max_length=30)),
                ('is_running', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Movie')),
            ],
            options={
                'db_table': 'play',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'screen',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.City')),
            ],
            options={
                'db_table': 'theater',
            },
        ),
        migrations.AddField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Theater'),
        ),
        migrations.AddField(
            model_name='play',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Screen'),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('name', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='theater',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('name', 'theater')},
        ),
    ]
