# Generated by Django 2.1.11 on 2022-02-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
